apiVersion: v1
data:
  BACKUP_FROM: /gitlab-postgresql-data
  BACKUP_TARGET: gitlab-postgresql
  BACKUP_TO: /backup
  FULL_BACKUP_COUNT: "3"
kind: ConfigMap
metadata:
  labels:
    name: backup-config-gitlab-postgresql
    app: gitlab
    role: backup
  name: backup-config-gitlab-postgresql
  namespace: devops
