apiVersion: v1
data:
  BACKUP_FROM: /jenkins-home
  BACKUP_TARGET: jenkins
  BACKUP_TO: /backup
  FULL_BACKUP_NUMBER: "3"
kind: ConfigMap
metadata:
  labels:
    name: jenkins-backup-config
    app: jenkins
    role: backup
  name: jenkins-backup-config
  namespace: devops
