apiVersion: v1
data:
  BACKUP_FROM: /jenkins-home
  BACKUP_TARGET: jenkins
  BACKUP_TO: /backup
  FULL_BACKUP_COUNT: "3"
kind: ConfigMap
metadata:
  labels:
    name: backup-config-jenkins
    app: jenkins
    role: backup
  name: backup-config-jenkins
  namespace: devops
