apiVersion: v1
data:
  BACKUP_FROM: /gitlab-data
  BACKUP_TARGET: gitlab
  BACKUP_TO: /backup
  FULL_BACKUP_COUNT: "3"
kind: ConfigMap
metadata:
  labels:
    name: backup-config-gitlab
    app: gitlab
    role: backup
  name: backup-config-gitlab
  namespace: devops
