---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cumul-jenkins
  namespace: devops
  labels:
    name: backup-cumul-jenkins
    app: jenkins
    role: backup
    backup-policy: cumul
spec:
  schedule: "* */3 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            name: backup-cumul-jenkins
            app: jenkins
            role: backup
            backup-policy: cumul
        spec:
          restartPolicy: Never
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - jenkins
                  - key: role
                    operator: In
                    values:
                    - devops
                namespaces:
                - devops
                topologyKey: kubernetes.io/hostname 
          containers:
          - name: backup-cumul-jenkins
            image: registry.cn-shanghai.aliyuncs.com/hybfkuf/k8s-tools:v1.0
            imagePullPolicy: IfNotPresent
            command:
            - 'bash'
            - '-c'
            - '/srv/backup-script.sh'
            envFrom:
            - configMapRef:
                name: backup-config-jenkins
            env:
            - name: BACKUP_POLICY
              value: 'cumul'
            securityContext:
              privileged: true
            volumeMounts:
            - name: backup-script
              mountPath: /srv
            - name: jenkins-home
              mountPath: /jenkins-home
            - name: backup
              mountPath: /backup
          volumes:
          - name: backup-script
            configMap:
              name: backup-script
              defaultMode: 0700
          - name: jenkins-home
            persistentVolumeClaim:
              claimName: jenkins-home
              readOnly: true
          - name: backup
            nfs:
              server: 10.240.1.21
              #server: 10.250.13.31
              path: /srv/nfs/cicd
