---
apiVersion: v1
kind: Secret
metadata:
  name: backup-restic-jenkins-secret
  labels:
    app: backup-restic-jenkins
    role: backup
    backup-method: restic
stringData:
  RESTIC_PASSWORD: restic
