---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-restic-gitlab-postgresql
  namespace: devops
  labels:
    app: backup-restic-gitlab-postgresql
    role: backup
    backup-method: restic
spec:
  schedule: "5 */3 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: backup-restic-gitlab-postgresql
            role: backup
            backup-method: restic
        spec:
          restartPolicy: Never
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - gitlab-postgresql
                  - key: role
                    operator: In
                    values:
                    - devops
                namespaces:
                - devops
                topologyKey: kubernetes.io/hostname 
          hostname: backup-restic-gitlab-postgresql
          containers:
          - name: backup-restic-gitlab-postgresql
            image: registry.cn-shanghai.aliyuncs.com/hybfkuf/hybfkuf-backup:v1.0
            imagePullPolicy: IfNotPresent
            command:
            - 'bash'
            - '-c'
            - '/srv/backup-script-restic.sh'
            envFrom:
            - configMapRef:
                name: backup-restic-gitlab-postgresql-config
            env:
            - name: TZ
              value: 'Asia/Shanghai'
            - name: RESTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backup-restic-gitlab-postgresql-secret
                  key: RESTIC_PASSWORD
            securityContext:
              privileged: true
            volumeMounts:
            - name: gitlab-postgresql-data
              mountPath: /gitlab-postgresql-data
            - name: restic
              mountPath: /restic
            - name: rclone
              mountPath: /rclone
            - name: rdiff
              mountPath: /rdiff
            - name: backup-script-restic
              mountPath: /srv/backup-script-restic.sh
              subPath: backup-script-restic.sh
            - name: backup-script-rclone
              mountPath: /srv/backup-script-rclone.sh
              subPath: backup-script-rclone.sh
            - name: backup-script-rdiff
              mountPath: /srv/backup-script-rdiff.sh
              subPath: backup-script-rdiff.sh
          volumes:
          - name: gitlab-postgresql-data
            persistentVolumeClaim:
              claimName: data-gitlab-postgresql-0
              readOnly: true
          - name: restic
            nfs:
              server: 10.240.1.21
              path: /srv/nfs/restic
              readOnly: false
          - name: rclone
            nfs:
              server: 10.240.1.21
              path: /srv/nfs/rclone
              readOnly: false
          - name: rdiff
            nfs:
              server: 10.240.1.21
              path: /srv/nfs/rdiff
              readOnly: false
          - name: backup-script-restic
            configMap:
              name: backup-script-restic
              defaultMode: 0700
          - name: backup-script-rclone
            configMap:
              name: backup-script-rclone
              defaultMode: 0700
          - name: backup-script-rdiff
            configMap:
              name: backup-script-rdiff
              defaultMode: 0700
