---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recovery-restic-gitlab-postgresql
  labels:
    app: recovery-restic-gitlab-postgresql
    role: recovery
    recovery-method: restic
spec:
  replicas: 1
  #strategy:
  #  type: Recreate
  selector:
    matchLabels:
      app: recovery-restic-gitlab-postgresql
      role: recovery
      recovery-method: restic
  template:
    metadata:
      labels:
        app: recovery-restic-gitlab-postgresql
        role: recovery
        recovery-method: restic
    spec:
      hostname: recovery-restic-gitlab-postgresql
      restartPolicy: Always
      #tolerations:
      #- key: node.kubernetes.io/not-ready
      #  operator: Exists
      #  effect: NoExecute
      #  tolerationSeconds: 10
      #- key: node.kubernetes.io/unreachable
      #  operator: Exists
      #  effect: NoExecute
      #  tolerationSeconds: 10
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - gitlab-postgresql
              - key: role
                operator: In
                values:
                - devops
            namespaces:
            - devops
            topologyKey: kubernetes.io/hostname
      containers:
      - name: recovery-restic-gitlab-postgresql
        image: registry.cn-shanghai.aliyuncs.com/hybfkuf/hybfkuf-backup:v1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: backup-restic-gitlab-config
        env:
        - name: TZ
          value: 'Asia/Shanghai'
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backup-restic-gitlab-secret
              key: RESTIC_PASSWORD
        securityContext:
          privileged: true
        volumeMounts:
        - name: gitlab-postgresql-data
          mountPath: /gitlab-postgresql-data
        - name: restic
          mountPath: /restic
        - name: rclone
          mountPath: /rclone
        - name: rdiff
          mountPath: /rdiff
        - name: backup-script-restic
          mountPath: /srv/backup-script-restic.sh
          subPath: backup-script-restic.sh
        - name: backup-script-rclone
          mountPath: /srv/backup-script-rclone.sh
          subPath: backup-script-rclone.sh
        - name: backup-script-rdiff
          mountPath: /srv/backup-script-rdiff.sh
          subPath: backup-script-rdiff.sh
      volumes:
      - name: gitlab-postgresql-data
        persistentVolumeClaim:
          claimName: data-gitlab-postgresql-0
          readOnly: false
      - name: restic
        nfs:
          server: 10.240.1.21
          #path: /srv/nfs/restic
          path: /srv/nfs/cicd
          readOnly: false
      - name: rclone
        nfs:
          server: 10.240.1.21
          path: /srv/nfs/rclone
          readOnly: false
      - name: rdiff
        nfs:
          server: 10.240.1.21
          path: /srv/nfs/rdiff
          readOnly: false
      - name: backup-script-restic
        configMap:
          name: backup-script-restic
          defaultMode: 0700
      - name: backup-script-rclone
        configMap:
          name: backup-script-rclone
          defaultMode: 0700
      - name: backup-script-rdiff
        configMap:
          name: backup-script-rdiff
          defaultMode: 0700
