---
apiVersion: v1
kind: Secret
metadata:
  name: backup-restic-gitlab-postgresql-secret
  labels:
    app: backup-restic-gitlab-postgresql
    role: backup
    backup-method: restic
stringData:
  RESTIC_PASSWORD: restic
