apiVersion: v1
data:
  BACKUP_FROM: /openldap-config
  BACKUP_TARGET: openldap-config
  BACKUP_TO: /backup
  FULL_BACKUP_COUNT: "3"
kind: ConfigMap
metadata:
  labels:
    name: backup-config-openldap-config
    app: openldap
    role: backup
  name: backup-config-openldap-config
  namespace: devops
